=pod

=for :prelude  Please pay close attention to the following.

=for :postlude Thank you for your attention.

=head1 DESCRIPTION

=encoding utf8

This is a simple document meant to be used in testing Pod::Weaver.

Glory to Queensrÿche!

=head1 BE FOREWARNED

This is not supported:

  much at all

Happy haĉking!

=encoding UTF-8

=head1 SYNOPSIS

This should probably get moved up front.

=attr is_awesome

(This is true by default.)

=cut
