=pod

=for :prelude  Please pay close attention to the following.

=for :postlude Thank you for your attention.

=head1 DESCRIPTION

This is a simple document meant to be used in testing Pod::Weaver.

It does not do very much.

=head1 ATTRIBUTES

This is a header that should be above the attributes list.

=head1 BE FOREWARNED

This is not supported:

  much at all

Happy hacking!

=head1 METHODS

=head1 SYNOPSIS

This should probably get moved up front.

=attr is_awesome

(This is true by default.)

=method do_something

Does something as a class method.

=head3 This is a leftover

Shouldn't be nested inside of do_something.

=cut
